version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.17.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
workflows:
  version: 2.1
  build:
    jobs:
      - build
