version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.17.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
  test:
    docker:
      - image: circleci/node:12.17.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install

workflows:
  version: 2.1
  build:
    jobs:
      - master
